version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
    info_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ../log/info/info.log
        maxBytes: 52428800
        backupCount: 20
        encoding: "utf8"
    debug_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../log/debug/debug.log
        maxBytes: 52428800
        backupCount: 20
        encoding: "utf8"
    warning_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: simple
        filename: ../log/warning/warning.log
        maxBytes: 52428800
        backupCount: 20
        encoding: "utf8"
    error_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ../log/error/error.log
        maxBytes: 52428800
        backupCount: 20
        encoding: "utf8"

loggers:
    infoLogger:
        level: INFO
        handlers: [console, info_handler]
        propagate: no
    debugLogger:
        level: DEBUG
        handlers: [console, debug_handler]
        propagate: no
    warningLogger:
        level: WARNING
        handlers: [console, warning_handler]
        propagate: no
    errorLogger:
        level: ERROR
        handlers: [console, error_handler]
        propagate: no
roots:
    level: DEBUG
    handlers: [console]
    propagate: true