version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ../log/info/info.log
        maxBytes: 52428800
        backupCount: 20
        encoding: "utf8"
    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../log/debug/debug.log
        maxBytes: 52428800
        backupCount: 20
        encoding: "utf8"
    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: simple
        filename: ../log/warning/warning.log
        maxBytes: 52428800
        backupCount: 20
        encoding: "utf8"
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ../log/error/error.log
        maxBytes: 52428800
        backupCount: 20
        encoding: "utf8"

loggers:
    fileLogger:
        level: DEBUG
        handlers: [console, info_file_handler,debug_file_handler,
        warning_file_handler, error_file_handler]
        propagate: no
roots:
    level: DEBUG
    handlers: [console]
    propagate: true